alertmanager:
  build: .
  container_name: alertmanager
  restart: unless-stopped
  ports:
    - "9093:9093"
  command:
    - "--config.file=/etc/alertmanager/alertmanager.yml"
    - "--storage.path=/alertmanager"
  volumes:
    - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    - alertmanager_data:/alertmanager
